version: '2'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: on-failure
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - TZ=America/Sao_Paulo
    ports:
      - 80:8888
    networks:
      - app-network  

  db:
    image: hypriot/rpi-mysql
    container_name: mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - TZ=America/Sao_Paulo
    networks:
      - app-network  
    ports:
      - 3306:3306
    volumes:
      - /data/db:/var/lib/mysql

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - /mosquitto/data:/mosquitto/data
      - /mosquitto/log:/mosquitto/log
      - /mosquitto/config:/mosquitto/config:ro
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

